version: '3'

services:
  illa:
    image: illasoft/illa-builder:latest
    restart: unless-stopped
    container_name: illa
    ports:
      - "127.0.0.1:3661:3661"
    volumes:
      - /home/devops/illa/database:/opt/illa/database
      - /home/devops/illa/drive:/opt/illa/drive
    labels:
      com.centurylinklabs.watchtower.enable: "true"
